#!/bin/bash
# Argument to the script is a valid ssh key for github, create a tag if it's a push to master (and not a tag)
# Push a new tag for every commit to master

if [ -z "$CODEBUILD_GIT_TAG" ] && [ "${CODEBUILD_PULL_REQUEST}" = "false" ] && [ "${CODEBUILD_GIT_BRANCH}" = "master" ]
then
	GIT_TAG=v$(date "+%Y%m%d-%H%M%S")
	echo "==> Tagging this release with $GIT_TAG"
	git config user.email "${CODEBUILD_GIT_AUTHOR_EMAIL}"
	git config user.name "${CODEBUILD_GIT_AUTHOR}"
	mkdir -p ~/.ssh/ && ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts 
	git remote set-url origin $(echo $CODEBUILD_SOURCE_REPO_URL | sed 's/https:\/\/github.com\//git@github.com:/g')
	echo "$1" > /tmp/key.pem && chmod 600 /tmp/key.pem
	eval $(ssh-agent) && ssh-add /tmp/key.pem 
	git tag $GIT_TAG -f -a -m "${CODEBUILD_GIT_MESSAGE}" -m "${CODEBUILD_BUILD_URL}"
	git push -q --tags
	rm /tmp/key.pem
fi
